### PR TITLE
Fix comment block in _normalize.scss

### PR DESCRIPTION
**Pull request by szepeviktor**
```scss
  /**
   * Nicely indented comment blocks.
   */
```

May be worth reading: https://github.com/sindresorhus/modern-normalize/tree/main#differences-from-normalizecss

### CODE REVIEW

**Comment by adamlaki** [comment]
Thank you Viktor!

Yeah, I know about the modern normalize. I write it up, I will look into it.

**Comment by adamlaki** [comment]
@szepeviktor https://github.com/conedevelopment/sprucecss/actions/runs/5901808183/job/16008647541 😢

**Comment by szepeviktor** [comment]
Please enable CI for PR-s.
Then I fix it.

**Comment by adamlaki** [comment]
What should I enable explicitly?

**Comment by szepeviktor** [comment]
Running the single workflow this repo has on pull requests.

https://github.com/conedevelopment/sprucecss/blob/15318158ba0e7940be3be52e711d8a75b70a2a48/.github/workflows/test.yml#L3-L5

**Comment by adamlaki** [comment]
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
```

So modify it to this?

**Comment by szepeviktor** [comment]
> So modify it to this?

Yes.
When some open a PR CI will run.

**Comment by adamlaki** [comment]
Thank you, modified!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
