### PR TITLE
Ignore Stylelint rules in SCSS files

### PR DESCRIPTION
**Pull request by szepeviktor**
... instead of ignoring them in the Stylelint configuration.

So further violations **will** pop up!
Lovely 5 line config file 🤩

Please consider doing this in other projects.

### CODE REVIEW

**Comment by adamlaki** [comment]
I am on the fence with this. Right now just these 4 modification needed?

**Comment by szepeviktor** [comment]
> Right now just these 4 modification needed?

Righty-right!

**Comment by szepeviktor** [comment]
Let's say you have four violations and one of them is intentional (false positive).
If you ignore a rule in the config file all four will vanish 〰

**Comment by adamlaki** [comment]
@szepeviktor not forgotten. After the release of the admin theme (in the next 2-3 weeks), I will come to Spruce (both CSS and UI) for a bigger iteration. Thanks for the reminder!

**Comment by szepeviktor** [comment]
@adamlaki I am planning to close this on the 4th _monthiversary_

**Comment by szepeviktor** [comment]
@adamlaki I would like to contribute again but emotionally blocked my the above ignoring method.

**Comment by adamlaki** [comment]
@szepeviktor, you know you are welcome, Viktor. The config - as it is now - was just easier for me, that's all. 

What would prettier solve? The alphabetizing? We can ditch stylelint for prettier?

**Comment by szepeviktor** [comment]
> What would prettier solve? The alphabetizing? Can we ditch Stylelint for prettier?

Stylelint v16 dropped formatting features. Those features could be added back by installing Prettier.

**Comment by szepeviktor** [comment]
Prettier is not easy.
```diff
-@mixin generate-table(
-  $selector: '.table',
-  $has-variations: true,
-  $has-responsive-table: true
-) {
+@mixin generate-table($selector: '.table', $has-variations: true, $has-responsive-table: true) {
```
e.g. I don't know how to prevent this change.
You won't be happy with prettier-ignore comments.

**Comment by adamlaki** [comment]
I understand; thanks for the clarification!

Well, the example is not so ideal. We have so much mixin where the line-breaking helps visually. I will try to look into it.

**Pull request closed without merging**
